---
## Run the defined checks before committing code to the remote repo. This should catch
## simple violations early and lessens the amount of pipeline failures.
#
## Every time you clone a project using pre-commit running `pre-commit install` should always be the
## first thing you do.
#
## IMPORTANT: For pre-commit to work, this file must carry the extension `.yaml`, NOT `.yml`.
#
## == Install the git hook scripts
## run `pre-commit install` to set up the git hook scripts. Now pre-commit will run automatically
## on git commit.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude_types:
          - jpeg
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: lint-yaml
        name: lint-yaml
        language: script
        entry: /bin/bash -c 'docker compose up lint-yaml --exit-code-from lint-yaml'
  - repo: local
    hooks:
      - id: lint-folders
        name: lint-folders
        language: script
        entry: /bin/bash -c 'docker compose up lint-folders --exit-code-from lint-folders'
  - repo: local
    hooks:
      - id: lint-filenames
        name: lint-filenames
        language: script
        entry: /bin/bash -c 'docker compose up lint-filenames --exit-code-from lint-filenames'
  - repo: local
    hooks:
      - id: lint-dockerfile-app
        name: lint-dockerfile-app
        language: script
        entry: /bin/bash -c 'docker compose up lint-dockerfile-app --exit-code-from lint-dockerfile-app'
  - repo: local
    hooks:
      - id: lint-dockerfile-docs
        name: lint-dockerfile-docs
        language: script
        entry: /bin/bash -c 'docker compose up lint-dockerfile-docs --exit-code-from lint-dockerfile-docs'
  - repo: local
    hooks:
      - id: lint-go
        name: lint-go
        language: script
        entry: /bin/bash -c 'docker compose up lint-go --exit-code-from lint-go'
  - repo: local
    hooks:
      - id: docker-compose-build
        name: docker-compose-build
        language: script
        entry: /bin/bash -c '(docker compose build)'
