---
# This Docker Compose file ... lint and build app ...
# build is for local, workflows use other ways
# lint is for local and actions workflow


version: "3.3"
services:

  filenames:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-filenames
    image: lslintorg/ls-lint:1.11.2
    volumes:
      - .:/data
    working_dir: /data

  folders:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-folders
    image: sommerfeldio/folderslint:latest
    volumes:
      - .:/data
    working_dir: /data
    command: folderslint

  yaml:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-yaml
    image: cytopia/yamllint:latest
    volumes:
      - .:/data
    working_dir: /data
    command: .
    tty: true

  dockerfile:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-dockerfile
    image: hadolint/hadolint:latest
    volumes:
      - .:/data
    working_dir: /data
    entrypoint: hadolint Dockerfile
    depends_on:
      - filenames
      - folders
      - yaml

  build-app:
    container_name: ${COMPOSE_PROJECT_NAME}
    build: components/app
    image: local/${COMPOSE_PROJECT_NAME}:${DEV_TAG}
    depends_on:
      - dockerfile
