---
## This Docker Compose file handles three responsibilities:
##
## . Linting the project files to ensure they adhere to coding standards.
## . Building the source2adoc application.
## . Testing the application.
##
## When running docker-compose up, all services are orchestrated to execute sequentially, ensuring
## the project is linted, built, and tested efficiently within the Docker environment.
##
## [source, bash]
## ....
## docker compose build
## docker compose up
## ....
##
## In case the Antora docs are not up-to-date, after building the application, build the image without
## using the Docker cache: docker compose build --no-cache`
##
## == Integrations
## Several services from this Docker Compose file are used in the pipeline to ensure the projects
## adheres to the same rules and coding standards when build remotely in a Github Actions workflow.
## Several services are used in the projects pre-commit hooks as well.

services:
  lint-yaml:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-yaml
    image: cytopia/yamllint:latest
    volumes: &default-volumes
      - .:/workspaces/source2adoc
    working_dir: &default-workdir /workspaces/source2adoc
    command: .
    tty: &tty true

  lint-workflows:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-workflows
    image: rhysd/actionlint:latest
    volumes: *default-volumes
    working_dir: *default-workdir
    command: -color
    tty: *tty

  lint-filenames:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-filenames
    image: lslintorg/ls-lint:1.11.2
    volumes: *default-volumes
    working_dir: *default-workdir
    tty: *tty

  lint-folders:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-folders
    image: sommerfeldio/folderslint:latest
    volumes: *default-volumes
    working_dir: *default-workdir
    command: .
    tty: *tty

  lint-gherkin:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-gherkin
    image: node:22.6.0-alpine3.19
    volumes: *default-volumes
    working_dir: *default-workdir
    command:
      - /bin/ash
      - -c
      - |
        npm install -g gherkin-lint
        gherkin-lint components/test-acceptance/specs
    tty: *tty

  lint-go-app:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-go-app
    image: &lint-go-image docker/golangci-lint:1.60.3-go1.23.0
    volumes:
      - ./components/app:/workspaces/source2adoc/components/app
    working_dir: /workspaces/source2adoc/components/app
    command: &lint-go-cmd golangci-lint run -v
    tty: *tty

  lint-go-acceptance-tests:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-go-acceptance-tests
    image: *lint-go-image
    volumes:
      - ./components/test-acceptance:/workspaces/source2adoc/components/test-acceptance
    working_dir: /workspaces/source2adoc/components/test-acceptance
    command: *lint-go-cmd
    tty: *tty

  lint-dockerfile-app:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-dockerfile-app
    image: &lint-dockerfile-image hadolint/hadolint:latest
    volumes: *default-volumes
    working_dir: *default-workdir
    entrypoint: hadolint Dockerfile.app

  lint-dockerfile-docs:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-dockerfile-docs
    image: *lint-dockerfile-image
    volumes: *default-volumes
    working_dir: *default-workdir
    entrypoint: hadolint Dockerfile.docs

  app-test:
    container_name: ${COMPOSE_PROJECT_NAME}-app-test
    image: &golang-image golang:1.22.6-alpine3.19
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./components/app:/workspaces/source2adoc/components/app:rw
      - ./testdata:/workspaces/source2adoc/testdata:ro
    working_dir: /workspaces/source2adoc/components/app
    command:
      - /bin/ash
      - -c
      - |
        rm -rf $${TARGET_DIR}
        rm -f "$${COVERAGE_REPORT}"

        go mod download
        go mod tidy
        go fmt ./...
        go vet ./...
        go test -coverprofile="$${COVERAGE_REPORT}" ./...

        chown 1000:1000 go.sum
        chown 1000:1000 "$${COVERAGE_REPORT}"
        chown -R 1000:1000 $${TARGET_DIR}

        sed -i "s|$${OLD}|$${NEW}|g" "$${COVERAGE_REPORT}"
    environment:
      - COVERAGE_REPORT=go-code-coverage.out
      - OLD=github.com/sommerfeld-io/source2adoc
      - NEW=components/app
      - TARGET_DIR=/workspaces/source2adoc/target

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: local/${COMPOSE_PROJECT_NAME}:${DEV_TAG}
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes: *default-volumes
    working_dir: *default-workdir
    # command: --help
    command: --source-dir . --output-dir ./target
    depends_on:
      app-test:
        condition: service_completed_successfully
      # app-acceptance-test:
      #   condition: service_completed_successfully

  docs:
    container_name: ${COMPOSE_PROJECT_NAME}-docs
    image: local/${COMPOSE_PROJECT_NAME}-docs:${DEV_TAG}
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - 3080:3000
