= source2adoc
Sebastian Sommerfeld <sebastian@sommerfeld.io>
:github-org: sommerfeld-io
:project-name: source2adoc
:url-project: https://github.com/{github-org}/{project-name}
:github-actions-url: {url-project}/actions/workflows
:job: pipeline.yml
:badge: badge.svg

The link:https://github.com/sommerfeld-io/source2adoc[source2adoc] project aims to streamline the process of generating AsciiDoc documentation from inline comments within source code files. With a focus on simplicity and efficiency, this tool converts inline documentation into AsciiDoc files, tailored for seamless integration with link:https://antora.org[Antora], a powerful documentation site generator.

image:{github-actions-url}/{job}/{badge}[Github Badge, link={github-actions-url}/{job}]

* Documentation Website -> https://source2adoc.sommerfeld.io
* Github Repository -> {url-project}
* DockerHub -> https://hub.docker.com/r/sommerfeldio/{project-name}
* SonarCloud Summary -> https://sonarcloud.io/project/overview?id={github-org}_{project-name}
* Where to file issues -> {url-project}/issues

NOTE: This project is currently in its early stages and is still in the incubation phase. As a result, there are many moving parts and tasks that need to be completed. The project is currently incomplete and work is ongoing to further develop and enhance its functionality.

The primary objective of `source2adoc` is to facilitate the creation of comprehensive and well-structured documentation directly from code comments. By leveraging the familiar syntax of inline comments in a style similar to JavaDoc, developers can annotate their code, ensuring that insights and explanations are captured and preserved in the generated AsciiDoc files.

The app supports multiple source code languages. The common ground is, that these languages mark their comments through the hash-symbol (`#`).

* bash
* yaml and yml
* Vagrantfile
* Dockerfile
* Makefile
* Ruby

source2adoc does not aim at replacing or duplicating existing solutions like JavaDoc or GoDoc! We focus on languages that are not covered by existing solutions in a way we expect!

== Requirements and Features
The following section outlines the requirements and features of the `source2adoc` project. These requirements serve as a guideline for the development of the application and provide a clear overview of the expected functionality.

=== Output Location
Generated AsciiDoc files should be placed into an Antora module named `source2adoc`.

=== Initial Documentation Scope
Initially, the application will only consider code comments acting as header documentation for entire files. Documentation blocks for classes and functions may be considered in future iterations.

=== File Path Preservation
When generating documentation into the Antora module, the file path should be preserved. For instance, the source code file `src/main/Dockerfile` should result in the AsciiDoc file `docs/modules/source2adoc/pages/src/main/Dockerfile.adoc` (with `docs` being the root folder of the antora component).

=== Antora Component Root Folder
The root folder of the Antora component should be changeable via a command line parameter. When the parameter is empty, `docs` will serve as the fallback root folder.

=== File Metadata
The caption of the AsciiDoc file should automatically be set from the source code file's name. Additionally, the path of the source code file and the author (if specified within the code file) should be included in the generated AsciiDoc file. The actual text of the header docs should be rendered into the AsciiDoc file as well. This text will not be translated any further, it is taken as is, thus allowing to write AsciiDoc directly into the source code docs.

=== Comment Style
The code comment style should resemble JavaDoc but a double hash-symbol (`##`) as the marker for commented lines. That means the comment is different from "regular" comments and still allows to use metadata similar to JavaDoc (e.g. @author, @since, ... but not all of them - see https://en.wikipedia.org/wiki/JavaDoc). `@see` should generate an xref, @link should generate a static link.

== Usage
For detailed information on how to use the `source2adoc` application, take a look at the application's help output.

[source, bash]
....
docker run --rm sommerfeldio/source2adoc:latest --help
....

To generate documentation based on the inline comments in a source code file, execute the following command: `--source-dir` and `--output-dir` are relative to `--workdir`.

[source, bash]
....
docker run --rm --volume "$(pwd):$(pwd)" --workdir $(pwd) sommerfeldio/source2adoc:latest --source-dir ./src --output-dir ./docs
....

`source2adoc` is distributed as a Docker image only, so remember to always use a complete Docker command to run the application.

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issues labeled as risk (= some sort of risk or a technical debt) or security (= related to security issues)] are tracked as GitHub issue and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io.

// +---------------------------------------------------+
// |                                                   |
// |        DO NOT EDIT DIRECTLY !!!!!                 |
// |                                                   |
// |        File is auto-generated by pipeline.        |
// |        Contents are based on Antora docs.         |
// |                                                   |
// +---------------------------------------------------+
