Feature: Well-structured Antora module generation

  As a user of the source2adoc CLI tool, I want to generate all mandatory files and update all needed
  information in existing files so that I can create a well-structured Antora module.

  Background:
    Given I am using the antora command of the source2adoc CLI tool

  Scenario: Generate navigation file for module
    Given todo ...
    When todo ...
    Then todo ...

  Scenario: Include moldule in component config
    Given todo ...
    When todo ...
    Then todo ... antora.yml ...
