= Global Requirements
Sebastian Sommerfeld <sebastian@sommerfeld.io>

This section outlines the global requirements for the `source2adoc` project, which aims to generate AsciiDoc documentation based on inline comments from source code files.

== Project Overview
The `source2adoc` project is tasked with automatically generating AsciiDoc documentation from inline comments found within source code files. The application should support multiple source code languages, including bash, YAML, Vagrantfile, Dockerfile, Makefile, and Ruby. Comments in these files will be marked using the hash-symbol (`#`).

CAUTION: Do not replace or duplicate existing solutions like JavaDoc or GoDoc! Make sure to focus on languages that are not covered by existing solutions in a way we expect!

== Command Line Parameter
The application must accept a command line parameter to specify the source code language to be considered. Only one option is allowed per run. To generate AsciiDoc documentation for multiple languages, the application must be executed multiple times with different language settings.

== Output Location
Generated AsciiDoc files should be placed into an Antora module named `source2adoc`. It is crucial not to delete the entire module and regenerate it from scratch with each application run, as this would prevent running the application multiple times for different languages.

== Initial Documentation Scope
Initially, the application will only consider code comments acting as header documentation for entire files. Documentation blocks for classes and functions may be considered in future iterations.

== File Path Preservation
When generating documentation into the Antora module, the file path should be preserved. For instance, the source code file `src/main/Dockerfile` should result in the AsciiDoc file `docs/modules/source2adoc/pages/src/main/Dockerfile.adoc` (with `docs` being the root folder of the antora component).

== Antora Component Root Folder
The root folder of the Antora component should be changeable via a command line parameter. When the parameter is empty, `docs` will serve as the fallback root folder.

== File Metadata
The caption of the AsciiDoc file should automatically be set from the source code file's name. Additionally, the path of the source code file and the author (if specified within the code file) should be included in the generated AsciiDoc file. The actual text of the header docs should be rendered into the AsciiDoc file as well. This text will not be translated any further, it is taken as is, thus allowing to write AsciiDoc directly into the source code docs.

== Comment Style
The code comment style should resemble Javadoc but use the hash-symbol (`#`) as the marker for commented lines. That means the marker for metadata should be similar to Javadoc (e.g. @author, @since, ... but not all of them - see https://en.wikipedia.org/wiki/Javadoc). `@see` should generate an xref, @link should generate a static link

== Dedicated Docker Image and Website
A dedicated Docker image should be generated for hosting the project's documentation website. This image will contain a website generated with Antora and should be published as `source2adoc.sommerfeld.io`. The GitHub project for hosting this website should be named `source2adoc-website`.

DockerHub serves as our only artifact repository for storing and distributing all images related to this app.
