= How this project is structured
Sebastian Sommerfeld <sebastian@sommerfeld.io>

== Filesystem Structure
TODO ... something about components, docs, Dockerfiles, docker-compose, ...

== Pipeline
The build pipeline is triggered by a commit to any branch in the repository. But not all branches are treated equally. The `main` branch is the most important branch in the repository. It is the branch that is always deployable and is the branch that is used to deploy to production. Other branches use a subset of the pipeline to ensure that they can be merged into the `main` branch and are are in a deployable state.

[plantuml, bar, svg]
....
@startuml

skinparam backgroundColor white
skinparam activity {
    'FontName Ubuntu
    FontName Roboto
}

|Scheduled|
    start
    :Dependabot;
    floating note left: Dependabot\ncreates Branches

|All Branches|
    start
    floating note right: Start here\nwithout Dependabot
    split
        :Run Linters;
    split again
        :Generate Docs;
    end split

    split
        :Scan Code;
        kill
    split again
        :Build and\nUnit Tests and\nAcceptance Tests;
    end split

    :Publish Artifact as Release Candidate;
    :Validate Release Candidate;

|Branch: main|
    if (release?) then (no)
        stop
    else (yes)
        :Create Git Tag\nand GitHub Release;
    endif

|Tag|
    :Publish Artifact\nas Release;
    :Validate Release;
    stop

@enduml
....

== Docker Image Build
The Docker image build process is separated into multiple steps. The image is a Multi-Stage Dockerfile to ensure that the final image is as small as possible with as few dependencies as possible. Part of the build process is to run unit tests and acceptance tests to ensure that the image is working as expected. For more information, see link:https://github.com/sommerfeld-io/source2adoc/blob/main/Dockerfile.app[Dockerfile.app].

=== Acceptance Tests
We use acceptance tests to ensure that the source2adoc CLI tool works as expected. The acceptance tests are written in Gherkin and can be found in the `link:https://github.com/sommerfeld-io/source2adoc/tree/main/components/test-acceptance/specs[components/test-acceptance/specs]` directory. We run the same set of tests locally from the IDE and as part of the Docker image build.

The simplest way to run the acceptance tests is to use the `docker compose up acceptance-test` command. This command will build a binary of the app and runs the acceptance tests against the app. This is intended to be used in the local development environment.

However, the actual build breaker is the Docker image build itself where the acceptance tests are run in a dedicated stage against the binary inside the image.
