= ADR-005: Code Comment Style
Sebastian Sommerfeld <sebastian@sommerfeld.io>

[cols="1,6"]
|===
|Status |Approved
|Decision Date |2024-05-23
|Decision | `##` will be the comment marker for source2adoc comments
|===

== Context
We are developing a CLI application in Go to parse inline comments from code files (e.g., Dockerfiles, Vagrantfiles, Bash scripts, YAML files, and Ruby files) and convert specially marked comments into AsciiDoc format. All these languages use `#` to mark comments. We need to choose a distinct marker to identify the relevant comments that should be converted because not every commented line is relevant and should be part of an AsciiDoc page.

== Comparison of Options
We considered three different markers for identifying the special comments:

. `###`
. `#...`
. `##`

=== `###`
==== Pros
- **Readability**: Visually distinct and easy to spot.
- **Simplicity**: Minimal changes required if `#` is already used for comments.
- **Compatibility**: Naturally compatible with most file types that use `#` for comments.

==== Cons
- **Conflict**: Might conflict with existing conventions in Markdown and tools that use `###` for headings or other purposes (although this should not be an issue because the comments themselves should contain AsciiDoc markup).

=== `#...`
==== Pros
- **Uniqueness**: Less likely to conflict with existing comment conventions.
- **Clarity**: Clearly distinguishable from regular comments.
- **Compatibility**: Naturally compatible with most file types that use `#` for comments.
- ** Usability**: Easy to remember and use, easy to type without the need to use Shift (which `#___` would require).

==== Cons
- **Readability**: Slightly less readable and recognizable compared to `###`.

=== `##`
==== Pros
- **Simplicity**: Easy to identify and use.
- **Compatibility**: Naturally compatible with most file types that use `#` for comments.
- ** Usability**: Easy to remember and use, easy to type with each new line.

==== Cons
- **Potential Misuse**: Less unique than `#...`, which could occasionally lead to ambiguity if `##` is used in another context within comments.

== Decision
We have decided to use `##` as the comment marker for special comments. This choice provides a good balance between simplicity, clarity, and compatibility across various file types plus is easy to type with each new line.
