##
# Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
# ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
# dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
# amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
# invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
# justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
# dolor sit amet.
#
# CAUTION: This is a file from the test data set
#
# Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
# ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
# dolores et ea rebum.
#
# Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
# ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
# dolores et ea rebum.
#
# Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
# ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
# dolores et ea rebum.
#
# CAUTION: This is a file from the test data set
##

FROM alpine:3.19.1 AS run
LABEL maintainer="sebastian@sommerfeld.io"

RUN echo "I am just a dummy for testing purposes"
