# -*- mode: ruby -*-
# vi: set ft=ruby :

##
# Todo header docs
##

IMAGE_NAME = "ubuntu/oracular64"
HOSTNAME = "testbox"

Vagrant.configure("2") do |config|
	config.vm.box = IMAGE_NAME
	config.vm.hostname = HOSTNAME

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
		v.name = HOSTNAME
	end
end
