---
## This file defines a GitHub Actions workflow for releasing the project. The purpose of this
## workflow is to automate the release process of the project. It specifies the steps and
## conditions for creating a release whenever a new tag and GitHub release is pushed to the
## repository.

name: Release Pipeline

on:
  release:
    types: [created]

env:
  IMAGE_TAG_RC: rc
  IMAGE_TAG_LATEST: latest
  IMAGE_NAME: source2adoc

jobs:
  publish-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Antora build
        run: docker compose up docs-build --exit-code-from docs-build
        shell: bash
      - name: Deploy via FTP
        run: |
          (
            cd target/docs/public || exit
            ls -alF
            docker run -i --rm \
              --volume "$(pwd):$(pwd)" \
              --workdir "$(pwd)" \
              sommerfeldio/ftp-client:latest ncftpput -R -v -u "${{ secrets.FTP_USER }}" -p "${{ secrets.FTP_PASS }}" "${{ secrets.FTP_HOST }}" / ./*
          )
        shell: bash

  publish-release:
    runs-on: ubuntu-latest
    env:
      DOCS_FILE: README # with path, without extension
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy to DockerHub
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG#v}"

          echo "New version tag = $TAG"

          docker pull "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}"

          docker tag "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}" "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}"
          docker tag "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}" "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:$TAG"

          docker push "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}"
          docker push "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:$TAG"
        shell: bash
      - name: Convert ${{ env.DOCS_FILE }} from Asciidoc to Markdown for DockerHub description
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc asciidoc
          asciidoc -b docbook ${{ env.DOCS_FILE }}.adoc
          mv ${{ env.DOCS_FILE }}.xml ./UPLOAD.xml
          pandoc -f docbook -t markdown_strict UPLOAD.xml -o UPLOAD.md
        shell: bash
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./UPLOAD.md

  validate-release:
    runs-on: ubuntu-latest
    needs: ['publish-release']
    permissions:
      contents: read
    steps:
      - name: Pull ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}
        run: docker pull ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}
        shell: bash
      - name: Compare digests
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG#v}"

          rc_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}")
          latest_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}")
          tag_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:$TAG")

          if [ "$rc_digest" != "$latest_digest" ] || [ "$rc_digest" != "$tag_digest" ] || [ "$tag_digest" != "$latest_digest" ]; then
            echo "[ERROR] Images are not identical"
            echo "[ERROR]   :latest | $latest_digest"
            echo "[ERROR]       :rc | $rc_digest"
            echo "[ERROR] exit code 1"
            exit 1
          else
            echo "[INFO] Images are identical"
            echo "[INFO] exit code 0"
          fi
        shell: bash

  docker-scout-cves-release:
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      contents: read
    env:
      CHEF_LICENSE: accept-no-persist
      CONTAINER_NAME: system_under_test
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Scout CVEs for ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}
        uses: docker/scout-action@v1.13.0
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}
          exit-code: false
          #write-comment: ${{ github.event_name == 'pull_request' }}
          write-comment: true
