---
name: Pull Request Analysis and AI Review

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  security-events: write

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/init@v3.25.12
        with:
          languages: java-kotlin
      - name: Build and analyze code
        uses: github/codeql-action/analyze@v3.25.12
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3.25.12
        with:
          sarif_file: codeql-results/results.sarif

      - name: Comment on PR with CodeQL results
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('codeql-results/results.sarif', 'utf8');
            const comment = `CodeQL analysis results:\n\n\`\`\`\n${results}\n\`\`\``;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
